"""Read VIZ (visual inspection zone) field values off the document image.

Same technique as the MRZ, same shared machinery (core/textgrid.py): the
document is generated by us, so the font, cell size and exact bounding box
of every field are known in advance (core/fields.py). This is a template
matcher for our own known layout, not a general OCR engine -- see
docs/06 in the SIH-2026 plan for why that trade-off is deliberate.
"""
from __future__ import annotations

import numpy as np

from config import FONTS, MODEL_FILES
from core.fields import VIZ_CELL_H, VIZ_CELL_W, VIZ_CHARSET, VIZ_LAYOUT
from core.textgrid import get_templates, read_char_grid

FONT_SIZE = 19


def get_viz_templates():
    return get_templates(MODEL_FILES["viz_glyphs"], VIZ_CHARSET, FONTS["mono_bold"],
                          FONT_SIZE, VIZ_CELL_W, VIZ_CELL_H)


def read_field(gray: np.ndarray, key: str) -> tuple[str, list[float]]:
    """Read one named VIZ field (a key from core.fields.VIZ_LAYOUT)."""
    templates = get_viz_templates()
    layout = VIZ_LAYOUT[key]
    return read_char_grid(gray, layout["value_bbox_xywh"], layout["n_cols"], templates)


def read_all_fields(gray: np.ndarray) -> dict[str, str]:
    return {key: read_field(gray, key)[0] for key in VIZ_LAYOUT}


if __name__ == "__main__":
    t = get_viz_templates()
    print(f"{len(t)} VIZ glyph templates ready, cell {VIZ_CELL_W}x{VIZ_CELL_H}, "
          f"cached at {MODEL_FILES['viz_glyphs']}")
